---
- hosts: buildah
  
  vars:
    dns: "1.1.1.1"

  tasks:  
  - name: Disable incorrect version of nodejs
    command: dnf module disable nodejs -y

  - name: Enable correct version of nodejs
    command: dnf module enable nodejs:16 -y

  - name: Install nodeJS
    package: 
      name: 
        - nodejs
        - git
        - nginx
      state: present
      use: dnf

  - name: Download Cherry
    git:
      repo: https://github.com/open-source-at-illinois/cherry.git
      dest: /tmp/cherry  

  - name: Install npm dependencies
    community.general.npm:
      path: /tmp/cherry/web
      
  - name: Install npm dependencies pt2
    community.general.npm:
      name: react-scripts
      global: true

  - name: Build npm project
    command: npm run build
    args:
      chdir: /tmp/cherry/web

  - name: Create web directory
    ansible.builtin.file:
      path: "/var/www/cherry"
      state: "directory"
      owner: root
      mode: 0755
      setype: httpd_sys_rw_content_t

  - name: Move built project to prod folder
    ansible.builtin.copy:
      remote_src: yes
      dest: "/var/www/cherry"
      src: "/tmp/cherry"
      owner: root
      setype: httpd_sys_rw_content_t

  - name: Copy nginx config file
    ansible.builtin.copy:
      dest: "/etc/nginx/conf.d/cherry.conf"
      src: "cherry_template.j2"
      owner: root

